apiVersion: v1
kind: Namespace
metadata:
  name: grpcdemo
  labels:
    istio-injection: enabled
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: go-grpc-greeter-server
  name: go-grpc-greeter-server
  namespace: grpcdemo
spec:
  replicas: 10
  selector:
    matchLabels:
      app: go-grpc-greeter-server
  template:
    metadata:
      labels:
        app: go-grpc-greeter-server
    spec:
      containers:
      - image: ikovnatsky/go-grpc-greeter-server:latest
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 50m
            memory: 50Mi
        env:
          - name: GODEBUG
            value: http2debug=2
        name: go-grpc-greeter-server
        ports:
        - containerPort: 50051
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: go-grpc-greeter-server
  name: go-grpc-greeter-server
  namespace: grpcdemo
spec:
  ports:
  - port: 50051
    protocol: TCP
    targetPort: 50051
  selector:
    app: go-grpc-greeter-server
  type: ClusterIP
---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: go-grpc-greeter-server
  namespace: grpcdemo
spec:
  host: greeter.[redacted].com
  grpc: true
  prefix: /
  service: http://go-grpc-greeter-server:50051
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-grpc-greeter-client
  namespace: grpcdemo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-grpc-greeter-client
  template:
    metadata:
      labels:
        app: go-grpc-greeter-client
    spec:
      containers:
      - name: go-grpc-greeter-client
        image: docker.io/ikovnatsky/grpcurl:latest
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 50m
            memory: 50Mi
        command:
          - sleep
          - infinity
